management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
      exposure:
        include: '*'
      base-path: /manage
spring:
  datasource:
    url: jdbc:mysql://eu-cdbr-west-02.cleardb.net:3306/heroku_678028072bd1b46?reconnect=true&sslMode=DISABLED&autoReconnect=true
#    url: jdbc:mysql://localhost:3306/banks_api
    username: bdec6aecad4779
    password: 5a923bc8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#    to change base url of the backend