management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: GET
      exposure:
        include: '*'
      base-path: /manage
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banks_api
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
server:
  servlet:
    contextPath: /bank
#    to change base url of the backend